/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.pinot.common.request;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.21.0)", date = "2025-04-10")
public enum JoinType implements org.apache.thrift.TEnum {
  INNER(0),
  LEFT(1),
  RIGHT(2),
  FULL(3);

  private final int value;

  private JoinType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static JoinType findByValue(int value) { 
    switch (value) {
      case 0:
        return INNER;
      case 1:
        return LEFT;
      case 2:
        return RIGHT;
      case 3:
        return FULL;
      default:
        return null;
    }
  }
}
